### ISSUE TITLE
Nabar& banner by bishal bhatta

### ISSUE THREAD

**Issue by bishalbhatta1028** [saikanepal/Tourism_Front#6]
USER : @bishalbhatta1028 

Context : Create navbar and Hero section 

Features : List All the features this component will have , Tick them as you go and complete them

 1. Navbar  
 2 . Carousel Hero Section 
3.  Device responsive
Any other description you would want to add

**Comment by Sameerbk201** [comment]
@bishalbhatta1028 
Please follow the convention mentioned.
Br,

**Comment by Sameerbk201** [comment]
Nice Job @bishalbhatta1028 
Br
